### ISSUE TITLE
not working after latest update that adds more sfx

### ISSUE THREAD

**Issue by Lyroo** [Brittank88/DYLMWYTDA#1]
hi, i tried using this again today after more sfx was added a few days ago, got this error:

Traceback (most recent call last):
File "main.py", line 84, in <module>
File "main.py", line 81, in main
File "json\ init_.py", line 346, in loads
File "json\decoder.py", line 337, in decode
File "json\decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0 )
[15412] Failed to execute script 'main' due to unhandled exception!

was working fine before the new sfx

**Comment by Brittank88** [comment]
Huh, I'll look into it. Wonder if Colon changed anything to do with the file I was reading to get all the asset paths.

**Comment by Brittank88** [comment]
He's made the file I was reading non-public, so now I'll have to scrape the asset paths directly from the webpage.

**Comment by Brittank88** [comment]
Nevermind, I can't do that because he's also made the sound files themselves non-public.

**Comment by Brittank88** [comment]
I've released an update that (at least for me) works again!
